In [20]:
import pandas as pd

data_1 = pd.read_excel(r"C:\Users\2026trainees86\Downloads\Credit Availability.xlsx", sheet_name="2026")
data_1

d:\conda_envs\pyenv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Customer Code,Customer Name,Type,Clean Credit,Current Debt (Million Baht),Current Debt (Million Baht).1,Est. further amount,Est. Debt,Date,Estimate Amount,...,MMA,Price.1,nBMA,Price.2,iBMA,Price.3,MAA,Price.4,Higher Ester,Price.5
0,6901,Mitsubishi Chemical Corporation,Monomer,2500,1060.393,0.424157,0,NaN,2026-01-06 00:00:00,1060.393,...,NaN,72.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000000,"MRT Resins (Thailand) Co.,Ltd.",Monomer,89,33.808,0.379865,16.295,0.562955,2026-01-06 00:00:00,50.103,...,112,85,42,90,28,90,5,95,NaN,NaN
2,2000001,"Kansai Resin (Thailand) Co.,Ltd.",Monomer,50,15.737,0.31474,4.9,0.41274,2026-01-06 00:00:00,20.637,...,28,85,14,90,14,90,NaN,NaN,NaN,NaN
3,2000002,"DIC Siam Chemical Industry Co.,Ltd.",Monomer,175,57.934,0.331051,11.052,0.394206,2026-01-06 00:00:00,68.986,...,72,76,42,72,28,72,6,90,NaN,NaN
4,2000004,Allnex (Thailand) Ltd.,Monomer,32,13.619,0.425594,6.8,0.638094,2026-01-06 00:00:00,20.419,...,72,65,20,70,10,72,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,2001077,"HYDRO SANITARY (THAILAND) CO.,LTD.",CCS,6,1.336,0.222667,0,NaN,2026-01-01 00:00:00,1.336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
472,2001078,Phatuchaiyo steel and stainless,CCS,1,0,0,NaN,NaN,2026-01-01 00:00:00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
473,2001087,"Thai Metal Aluminium Co.,Ltd",CCS,2,0.399,0.1995,NaN,NaN,2026-01-01 00:00:00,0.399,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,2001093,โพลีปรีแฟบ แอนด์กลาส จำกัด,CCS,2,1.932,0.966,0.925,NaN,2026-01-01 00:00:00,2.857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,2001118,บริษัทเจริญรุ่งเรือง โลหะกิจ จำกัด,CCS,3,0.667,0.222333,0.925,NaN,2026-01-01 00:00:00,1.592,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data_1['Date'].dtypes

dtype('O')

In [21]:
data_1.columns

Index(['Customer Code', 'Customer Name', 'Type', 'Clean Credit',
       'Current Debt (Million Baht)', 'Current Debt (Million Baht).1',
       'Est. further amount ', 'Est. Debt', 'Date', 'Estimate Amount', 'CCS',
       'Price', 'MMA', 'Price.1', 'nBMA', 'Price.2', 'iBMA', 'Price.3', 'MAA',
       'Price.4', 'Higher Ester', 'Price.5'],
      dtype='str')

In [4]:
import pandas as pd

data_2 = pd.read_excel(r"C:\Users\2026trainees86\Downloads\Credit Availability.xlsx", sheet_name="2023")
data_2

,Customer Code,Customer Name,Type,Clean credit (MB),Current Debt (Million Baht),Est. further amount,Date,Estimate Amount,CCS,Price,MMA,Price.1,nBMA,Price.2,iBMA,Price.3,MAA,Price.4,Higher Ester,Price.5
0,6901.0,Mitsubishi Chemical Corporation,Monomer,3400.0,563.274,0.00000,2023-12-01,563.27400,NaN,72.24,NaN,72.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000000.0,"MRT Resins (Thailand) Co.,Ltd.",Monomer,89.0,48.387,8.66504,2023-12-01,57.05204,NaN,70.00,98.0,55.48,28.0,66.0,14.0,75.0,5.0,66.0,NaN,NaN
2,2000001.0,"Kansai Resin (Thailand) Co.,Ltd.",Monomer,50.0,22.647,3.23400,2023-12-01,25.88100,NaN,75.00,14.0,76.00,14.0,75.0,14.0,80.0,NaN,NaN,NaN,NaN
3,2000002.0,"Siam Chemical Industry Co.,Ltd.",Monomer,175.0,58.400,4.36056,2023-12-01,62.76056,NaN,70.00,24.0,55.69,28.0,72.0,14.0,72.0,NaN,NaN,NaN,NaN
4,2000004.0,Allnex (Thailand) Ltd.,Monomer,21.0,14.138,0.45500,2023-12-01,14.59300,NaN,70.00,0.0,53.03,7.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2042,2000783.0,"GTECH PRODUCTS CO., LTD",CCS,5.0,4.486,0.00000,2021-07-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2043,2000786.0,"GTECH OHM CO.,LTD.",CCS,4.0,1.814,0.00000,2021-07-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2044,2000787.0,GTS Variety,CCS,2.0,0.446,0.00000,2021-07-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2045,2000788.0,"GTECH STATION CO.,LTD.",CCS,4.0,2.495,0.00000,2021-07-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2046,2000762.0,อ.นำแสงไทย จำกัด,CCS,1.0,1.200,0.00000,2021-07-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data_2['Date'].dtypes

dtype('<M8[us]')

In [19]:
data_2.columns

Index(['Customer Code', 'Customer Name', 'Type', 'Clean credit (MB)',
       'Current Debt (Million Baht)', 'Est. further amount ', 'Date',
       'Estimate Amount', 'CCS', 'Price', 'MMA', 'Price.1', 'nBMA', 'Price.2',
       'iBMA', 'Price.3', 'MAA', 'Price.4', 'Higher Ester', 'Price.5'],
      dtype='str')